<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-254N2F8" ignored="4" name="Test" tests="3" failures="1" timestamp="11 Feb 2020 14:05:19 GMT" time="40.244" errors="0">
  <testcase name="check" time="0.008" classname="com.flipkart.testcase.LoginTestcase"/>
  <testcase name="check" time="0.006" classname="com.flipkart.testcase.RegisterTestCase"/>
  <testcase name="login" time="5.271" classname="com.flipkart.testcase.LoginTestcase">
    <failure type="java.lang.AssertionError" message="login error expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: login error expected [true] but found [false]
	at com.flipkart.testcase.LoginTestcase.login(LoginTestcase.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="@BeforeTest reportSetup" time="0.0" classname="com.flipkart.base.DriverCreation">
    <ignored/>
  </testcase> <!-- @BeforeTest reportSetup -->
  <testcase name="@BeforeTest reportSetup" time="0.0" classname="com.flipkart.base.DriverCreation">
    <ignored/>
  </testcase> <!-- @BeforeTest reportSetup -->
  <testcase name="@AfterTest endReport" time="0.0" classname="com.flipkart.base.DriverCreation">
    <ignored/>
  </testcase> <!-- @AfterTest endReport -->
  <testcase name="@AfterTest endReport" time="0.0" classname="com.flipkart.base.DriverCreation">
    <ignored/>
  </testcase> <!-- @AfterTest endReport -->
</testsuite> <!-- Test -->
